version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: meddy:v1
    ports:
      - "3000:3000"
    env_file:
      - .env
    working_dir: /usr/src/app
    command: ["./start.sh"]
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
